export const GET_MACHINES = "GET_MACHINES";
export const GET_MACINES_PENDING = "GET_MACHINES_PENDING";
export const GET_MACHINES_FULFILLED = "GET_MACHINES_FULFILLED";
export const GET_MACHINES_REJECTED = "GET_MACHINES_REJECTED";

export const SUBMIT_PAYMENT = "SUBMIT_PAYMENT";
export const SUBMIT_PAYMENT_PENDING = "SUBMIT_PAYMENT_PENDING";
export const SUBMIT_PAYMENT_FULFILLED = "SUBMIT_PAYMENT_FULFILLED";
export const SUBMIT_PAYMENT_REJECTED = "SUBMIT_PAYMENT_REJECTED";

export const SELECT_MACHINE = "SELECT_MACHINE";
export const SELECT_MACHINE_PENDING = "SELECT_MACHINE_PENDING";
export const SELECT_MACHINE_FULFILLED = "SELECT_MACHINE_FULFILLED";
export const SELECT_MACHINE_REJECTED = "SELECT_MACHINE_REJECTED";

export const HAS_MACHINE_CHANGED = "HAS_MACHINE_CHANGED";
