/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.machine.vending.app;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.web.servlet.config.annotation.CorsRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;

@SpringBootApplication
@ComponentScan(basePackages= {"com.machine","com.machine.vending", "com.machine.vending.model", "com.machine.vending.api"})
public class VendingApplication {
	
	@Bean
	public WebMvcConfigurer corsConfigurer() {
		return new WebMvcConfigurer() {
			
			@Override
			public void addCorsMappings(CorsRegistry registry) {
				registry.addMapping("/**")
				.allowedOrigins("*")
				.allowedMethods("GET","POST","PUT","OPTIONS","DELETE")
				.allowedHeaders("Content-Type", "X-Requested-With",
						"accept", "Origin",
						"Access-Control-Request-Method",
						"Access-Control-Request-Headers",
						"Access-Control-Allow-Origin");
			}
			
			/*
			@Override
			public void configureMessageConverters(List<HttpMessageConverter<?>> converters ) {
				MappingJackson2HttpMessageConverter converter = new MappingJackson2HttpMessageConverter();
				VendingMachineEntityModule machineModule = new VendingMachineEntityModule();
				final ObjectMapper mapper = new ObjectMapper();
				mapper.registerModule(machineModule);
				converter.setObjectMapper(mapper);
				converters.add(converter);
			}*/
		};
		
		
	}
	
    public static void main(String[] args) {
        SpringApplication.run(VendingApplication.class);
    }
}
